name: built_redux_thunk
version: 0.1.0
description:
   Thunks for built_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_thunk
dependencies:
  built_redux: ">=2.1.0 <6.0.0"
  built_value: ^4.1.0

dev_dependencies:
  build_runner: ^0.4.0
  built_value_generator: ^4.1.0
  test: ^0.12.0

environment:
  sdk: ">=1.17.1 <2.0.0"
