name: built_redux_thunk
version: 0.5.1
description:
  Thunks for built_redux
authors:
  - David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_thunk
dependencies:
  built_redux: ">=6.1.1 <8.0.0"
  built_value: '>=6.8.2 <8.0.0'

dev_dependencies:
  built_collection: ^4.3.0
  build_runner: ^1.10.0
  built_value_generator: ^7.0.0
  source_gen: ^0.9.4+6
  test: ^1.9.1
  build_test: ^1.2.0
  build_web_compilers: ^2.7.1

environment:
  sdk: '>=2.0.0-dev <3.0.0'